---
driver:
  name: vagrant

provisioner:
  name: policyfile_zero
  client_rb:
    audit_mode: :enabled

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    attributes:
