---
provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  - name: centos-6.5
    driver:
      name: vagrant
  - name: centos-6.5-aws
    driver:
      name: ec2
      aws_ssh_key_id: tpetchel
      security_group_ids: ["sg-49896b2e"]
      image_id: ami-b6bdde86
      region: us-west-2
      instance_type: m3.medium
      tags:
        "X-Project": "Learn Chef"
    transport:
      ssh_key: ~/.ssh/tpetchel.pem
      username: root
  # - name: centos-6.5-azure
  #   driver:
  #     name: azurerm
  #   driver_config:
  #     subscription_id: 'bacf2c23-fb3f-4dde-bc6e-9d242e21ffe7'
  #     location: 'East US'
  #     machine_size: 'Standard_D1'
  #     image_urn: OpenLogic:CentOS:6.5:latest

suites:
  - name: default
    run_list:
      - recipe[learn-the-basics-rhel::default]
    attributes:
