---
driver:
  name: vagrant

transport:
  username: Administrator
  password: Pass@word1

provisioner:
  name: chef_zero
  #chef_omnibus_install_options: -P chefdk
  client_rb:
    audit_mode: :enabled

verifier:
  name: inspec

platforms:
  - name: windows-2012R2
    driver:
      customize:
        memory: 2048
    driver_config:
      box: mwrock/Windows2012R2

suites:
  - name: default
    run_list:
      - recipe[learn-the-basics-windows::default]
    attributes:
